repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^.*__init__.py$
        stages: [commit, push, manual]

  - repo: https://github.com/hhatto/autopep8
    rev:  v2.0.4  # select the tag or revision you want, or run `pre-commit autoupdate`
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive, --max-line-length=79]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        files: requirements

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5' # Update me!
    hooks:
      - id: bandit

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=79
#    rev: 23.11.0
#    hooks:
#      - id: black
#        language_version: python3
#        args: [--line-length=79]
